# ========== Stages (ordre d'exécution) ==========
stages:
  - test
  - security
  - build
  - deploy_staging
  - deploy_production

variables:
  NODE_VERSION: "20"

# ========== Stage test : exécuter les tests Jest ==========
test:
  stage: test
  image: node:${NODE_VERSION}-alpine
  before_script:
    - npm ci
  script:
    - npm test

# ========== Stage security : détection de secret exposé ==========
security:
  stage: security
  image: alpine:latest
  script:
    - |
      set -eu
      echo "Running secret pattern scan..."
      FOUND=0

      if grep -RInE \
        "(^|[^a-zA-Z0-9_])[aA][pP][iI](_[kK][eE][yY])?[[:space:]]*=[[:space:]]*['\"]?[^'\" [:space:]]{6,}['\"]?" \
        --include="*.js" --include="*.ts" --include="*.json" \
        --include="*.env" --include="*.env.*" \
        --include="*.yml" --include="*.yaml" . 2>/dev/null; then
        FOUND=1
      fi

      if [ "$FOUND" -eq 1 ]; then
        echo "ERREUR : possible secret détecté (API= ou API_KEY=...)."
        exit 1
      fi

      echo "Aucun secret suspect détecté."

# ========== Stage build : construction de l'image Docker ==========
build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker info
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

  after_script:
    - echo "IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPO}:$CI_COMMIT_SHORT_SHA" > build.env
  artifacts:
    reports:
      dotenv: build.env


# ========== Deploy staging (AWS) : automatique sur branche develop ==========
deploy_staging:
  stage: deploy_staging
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  dependencies:
    - build
  script:
    - cd terraform/aws-staging
    - terraform init
    - terraform apply -auto-approve -var="image=$IMAGE_URI"
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

# ========== Deploy production (Azure) : manuel (gate) sur branche main ==========
deploy_production:
  stage: deploy_production
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  when: manual
  variables:
    TF_IN_AUTOMATION: "true"
  before_script:
    - terraform -version
    - test -n "$ARM_CLIENT_ID"
    - test -n "$ARM_CLIENT_SECRET"
    - test -n "$ARM_SUBSCRIPTION_ID"
    - test -n "$ARM_TENANT_ID"
    - test -n "$GL_REGISTRY_USER"
    - test -n "$GL_REGISTRY_TOKEN"
  script:
    - cd terraform/azure-production
    - terraform init
    - terraform apply -auto-approve -var="docker_image=$CI_REGISTRY_IMAGE" -var="docker_image_tag=latest" -var="registry_url=https://$CI_REGISTRY" -var="registry_user=$GL_REGISTRY_USER" -var="registry_password=$GL_REGISTRY_TOKEN"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"